"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Badge } from "@/components/ui/badge"
import { X, Save, Loader2 } from "lucide-react"
import { PhotoUpload } from "@/components/photo-upload"

interface AddEmployeeProps {
  onClose: () => void
  onSuccess: () => void
}

export function AddEmployee({ onClose, onSuccess }: AddEmployeeProps) {
  const [isSaving, setIsSaving] = useState(false)
  const [saveError, setSaveError] = useState("")
  const [profilePicture, setProfilePicture] = useState("")
  
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    role: "employee" as "admin" | "employee",
    department: "",
    position: "",
    phone: "",
    salary: "",
    companyName: ""
  })

  const handleInputChange = (field: string, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }))
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setSaveError("")
    setIsSaving(true)

    try {
      const response = await fetch('/api/employees', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          ...formData,
          salary: formData.salary ? parseFloat(formData.salary) : undefined,
          profilePicture: profilePicture || undefined
        })
      })

      const result = await response.json()

      if (result.success) {
        onSuccess()
        onClose()
      } else {
        setSaveError(result.error || "Failed to create employee")
      }
    } catch (error) {
      setSaveError("Failed to create employee")
    } finally {
      setIsSaving(false)
    }
  }

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <Card className="w-full max-w-2xl max-h-[90vh] overflow-y-auto">
        <CardHeader className="bg-gray-50 border-b border-gray-200">
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="text-xl text-black">Add New Employee</CardTitle>
              <CardDescription className="text-gray-600">
                Create a new employee account with profile information
              </CardDescription>
            </div>
            <Button variant="ghost" size="sm" onClick={onClose}>
              <X className="w-4 h-4" />
            </Button>
          </div>
        </CardHeader>
        
        <CardContent className="p-6">
          <form onSubmit={handleSubmit} className="space-y-6">
            {saveError && (
              <div className="p-3 bg-red-50 border border-red-200 rounded-lg text-sm text-red-600">
                {saveError}
              </div>
            )}

            {/* Profile Picture */}
            <div className="flex flex-col items-center">
              <Label className="text-sm font-medium text-black mb-3">Profile Picture</Label>
              <PhotoUpload
                currentPhoto={profilePicture}
                employeeId="" // Will be generated by the API
                onPhotoUpdate={setProfilePicture}
                size="lg"
              />
            </div>

            {/* Basic Information */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="name" className="text-black font-medium">Full Name *</Label>
                <Input
                  id="name"
                  value={formData.name}
                  onChange={(e) => handleInputChange("name", e.target.value)}
                  disabled={isSaving}
                  className="bg-white border-gray-300"
                  required
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="email" className="text-black font-medium">Email *</Label>
                <Input
                  id="email"
                  type="email"
                  value={formData.email}
                  onChange={(e) => handleInputChange("email", e.target.value)}
                  disabled={isSaving}
                  className="bg-white border-gray-300"
                  required
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="role" className="text-black font-medium">Role *</Label>
                <Select value={formData.role} onValueChange={(value: "admin" | "employee") => handleInputChange("role", value)}>
                  <SelectTrigger className="bg-white border-gray-300">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="employee">Employee</SelectItem>
                    <SelectItem value="admin">Admin</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="phone" className="text-black font-medium">Phone</Label>
                <Input
                  id="phone"
                  value={formData.phone}
                  onChange={(e) => handleInputChange("phone", e.target.value)}
                  disabled={isSaving}
                  className="bg-white border-gray-300"
                />
              </div>
            </div>

            {/* Job Information */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="department" className="text-black font-medium">Department *</Label>
                <Input
                  id="department"
                  value={formData.department}
                  onChange={(e) => handleInputChange("department", e.target.value)}
                  disabled={isSaving}
                  className="bg-white border-gray-300"
                  required
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="position" className="text-black font-medium">Position *</Label>
                <Input
                  id="position"
                  value={formData.position}
                  onChange={(e) => handleInputChange("position", e.target.value)}
                  disabled={isSaving}
                  className="bg-white border-gray-300"
                  required
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="salary" className="text-black font-medium">Salary</Label>
                <Input
                  id="salary"
                  type="number"
                  value={formData.salary}
                  onChange={(e) => handleInputChange("salary", e.target.value)}
                  disabled={isSaving}
                  className="bg-white border-gray-300"
                  placeholder="Annual salary"
                />
              </div>
              
              <div className="space-y-2">
                <Label htmlFor="companyName" className="text-black font-medium">Company Name</Label>
                <Input
                  id="companyName"
                  value={formData.companyName}
                  onChange={(e) => handleInputChange("companyName", e.target.value)}
                  disabled={isSaving}
                  className="bg-white border-gray-300"
                  placeholder="Optional"
                />
              </div>
            </div>

            {/* Actions */}
            <div className="flex gap-3 pt-4 border-t border-gray-200">
              <Button
                type="submit"
                disabled={isSaving}
                className="gap-2 bg-green-600 hover:bg-green-700 text-white px-6"
              >
                {isSaving ? (
                  <>
                    <Loader2 className="w-4 h-4 animate-spin" />
                    Saving...
                  </>
                ) : (
                  <>
                    <Save className="w-4 h-4" />
                    Create Employee
                  </>
                )}
              </Button>
              <Button
                type="button"
                variant="outline"
                onClick={onClose}
                disabled={isSaving}
                className="border-gray-300 text-gray-700 hover:bg-gray-50 px-6"
              >
                Cancel
              </Button>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  )
}
